version: '3.7'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2022!"
    ports:
      - "5432:5432"
  app:
      build: .
      ports:
        - "10000:10000"
      depends_on:
        - db
  